### ISSUE TITLE
Disciplines doesn't work after latest commit: TypeError: this.disciplinesDefinition is undefined

### ISSUE THREAD

**Issue by haterzlin** [haterzlin/character-sheet#100]
This is shown only if we do 

`npm run build`
`cd dist`
`python3 -m http.server 8000`

and 
`firefox localhost:8000`

**Comment by haterzlin** [comment]
We should also modify test process to discover this issue before merging in master

**Comment by longnicknam3** [comment]
mozno by som aj prerobil discipliny lebo co som sa dival na `discipline.vue` tak mi neni jasne co sa tam vlastne deje a robis tam tu istu vec, a je vidiet ze sa ti IDE snazilo pomoct, ale vypadol z toho tento bug
