### ISSUE TITLE
name input width

### ISSUE THREAD

**Issue by longnicknam3** [haterzlin/character-sheet#53]
bolo by pekne keby to nemalo pevnu sirku 100% ale aby sa sirka tohoto elementu nastavovala podla dlzky retazca, a v pripade name="" podla dlzky default name
problem je ze js toto nativne nevie, lebo string.length vraca inu hodnotu
funkcia co som na toto nasiel vypadala funkcne, pracovala s regularnymi vyrazmi, mala problem s retazcami typu "A "* cili retazce kde alternuje nejake pismeno a medzera

**Comment by haterzlin** [comment]
aktualne nema zmysel
